CC=mpicc

all: 1hintT0 2hintT0 3hintT0 4hintT0 5hintT0 6hintT0 7hintT0 8hintT0

1hintT0: 1hintT0.c
	$(CC) -o 1hintT0 -S -O3 1hintT0.c

2hintT0: 2hintT0.c
	$(CC) -o 2hintT0 -O3 2hintT0.c

3hintT0: 3hintT0.c
	$(CC) -o 3hintT0 -O3 3hintT0.c

4hintT0: 4hintT0.c
	$(CC) -o 4hintT0 -O3 4hintT0.c

5hintT0: 5hintT0.c
	$(CC) -o 5hintT0 -O3 5hintT0.c

6hintT0: 6hintT0.c
	$(CC) -o 6hintT0 -O3 6hintT0.c

7hintT0: 7hintT0.c
	$(CC) -o 7hintT0 -O3 7hintT0.c

8hintT0: 8hintT0.c
	$(CC) -o 8hintT0 -O3 8hintT0.c

clean:
	rm 1hintT0 2hintT0 3hintT0 4hintT0 5hintT0 6hintT0 7hintT0 8hintT0
