CC=mpicc

all: v1 nov1 t1 t2 1hintT0 2hintT0 3hintT0 4hintT0 5hintT0 6hintT0 7hintT0 8hintT0

v1: hint.c
	$(CC) -o v1 -O3 hint.c

nov1: nohint.c
	$(CC) -o nov1 -O3 nohint.c

t1: hintt1.c
	$(CC) -o t1 -O3 hintt1.c

t2: hintt2.c
	$(CC) -o t2 -O3 hintt2.c

1hintT0: 1hintT0.c
	$(CC) -o 1hintT0 -O3 1hintT0.c

2hintT0: 2hintT0.c
	$(CC) -o 2hintT0 -O3 2hintT0.c

3hintT0: 3hintT0.c
	$(CC) -o 3hintT0 -O3 3hintT0.c

4hintT0: 4hintT0.c
	$(CC) -o 4hintT0 -O3 4hintT0.c

5hintT0: 5hintT0.c
	$(CC) -o 5hintT0 -O3 5hintT0.c

6hintT0: 6hintT0.c
	$(CC) -o 6hintT0 -O3 6hintT0.c

7hintT0: 7hintT0.c
	$(CC) -o 7hintT0 -O3 7hintT0.c

8hintT0: 8hintT0.c
	$(CC) -o 8hintT0 -O3 8hintT0.c

clean:
	rm *.o
