CC=mpicc

all: max8 max7 max6 max5 max4 max3 max2 max1

max8: max8.c
	$(CC) -o max8 -O3 max8.c

max7: max7.c
	$(CC) -o max7 -O3 max7.c

max6: max6.c
	$(CC) -o max6 -O3 max6.c

max5: max5.c
	$(CC) -o max5 -O3 max5.c

max4: max4.c
	$(CC) -o max4 -O3 max4.c

max3: max3.c
	$(CC) -o max3 -O3 max3.c

max2: max2.c
	$(CC) -o max2 -O3 max2.c

max1: max1.c
	$(CC) -o max1 -O3 max1.c

clean: 
	rm -f max8 max7 max6 max5 max4 max3 max2 max1
