CC=mpicc

all: v1 nov1 t1 t2 1nohintT0 2nohintT0 3nohintT0 4nohintT0 5nohintT0 6nohintT0 7nohintT0 8nohintT0

v1: hint.c
	$(CC) -o v1 -O3 hint.c

nov1: nohint.c
	$(CC) -o nov1 -O3 nohint.c

t1: hintt1.c
	$(CC) -o t1 -O3 hintt1.c

t2: hintt2.c
	$(CC) -o t2 -O3 hintt2.c

1nohintT0: 1hintT0.c
	$(CC) -o 1nohintT0 -O3 1nohintT0.c

1nohintT0: 1hintT0.c
	$(CC) -o 1nohintT0 -O3 1hintT0.c

2nohintT0: 2hintT0.c
	$(CC) -o 2nohintT0 -O3 2hintT0.c

3nohintT0: 3hintT0.c
	$(CC) -o 3nohintT0 -O3 3hintT0.c

4nohintT0: 4hintT0.c
	$(CC) -o 4nohintT0 -O3 4hintT0.c

5nohintT0: 5hintT0.c
	$(CC) -o 5nohintT0 -O3 5hintT0.c

6nohintT0: 6hintT0.c
	$(CC) -o 6nohintT0 -O3 6hintT0.c

7nohintT0: 7hintT0.c
	$(CC) -o 7nohintT0 -O3 7hintT0.c

8nohintT0: 8hintT0.c
	$(CC) -o 8nohintT0 -O3 8hintT0.c

clean:
	rm *.o
