CC=mpicc

all: 1nohintT0 2nohintT0 3nohintT0 4nohintT0 5nohintT0 6nohintT0 7nohintT0 8nohintT0

1nohintT0: 1hintT0.c
	$(CC) -o 1nohintT0 -O3 1hintT0.c

2nohintT0: 2hintT0.c
	$(CC) -o 2nohintT0 -O3 2hintT0.c

3nohintT0: 3hintT0.c
	$(CC) -o 3nohintT0 -O3 3hintT0.c

4nohintT0: 4hintT0.c
	$(CC) -o 4nohintT0 -O3 4hintT0.c

5nohintT0: 5hintT0.c
	$(CC) -o 5nohintT0 -O3 5hintT0.c

6nohintT0: 6hintT0.c
	$(CC) -o 6nohintT0 -O3 6hintT0.c

7nohintT0: 7hintT0.c
	$(CC) -o 7nohintT0 -O3 7hintT0.c

8nohintT0: 8hintT0.c
	$(CC) -o 8nohintT0 -O3 8hintT0.c

clean:
	rm 1nohintT0 2nohintT0 3nohintT0 4nohintT0 5nohintT0 6nohintT0 7nohintT0 8nohintT0
